# Test Get Data

In [1]:
import os
import sys
from pathlib import Path

# Si le notebook est dans ./notebooks/, src est au niveau au-dessus
root = Path.cwd().parent if Path.cwd().name == "Notebook" else Path.cwd()
src_path = str(root / "src")

if src_path not in sys.path:
    sys.path.insert(0, src_path)


print(os.getcwd())
# test
# from mon_package.module import ma_fonction

c:\Users\User\AlexisGauthron\Projet\IA_create_IA_cate\Notebook

In [2]:
import analyse_donne.load_datasets as an

df = an.load_datasets_breast_cancer()
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [3]:
df = an.load_datasets_iris()
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [4]:
df = an.load_datasets_wine()
df

{'data':      alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
 0      14.23        1.71  2.43               15.6      127.0           2.80
 1      13.20        1.78  2.14               11.2      100.0           2.65
 2      13.16        2.36  2.67               18.6      101.0           2.80
 3      14.37        1.95  2.50               16.8      113.0           3.85
 4      13.24        2.59  2.87               21.0      118.0           2.80
 ..       ...         ...   ...                ...        ...            ...
 173    13.71        5.65  2.45               20.5       95.0           1.68
 174    13.40        3.91  2.48               23.0      102.0           1.80
 175    13.27        4.28  2.26               20.0      120.0           1.59
 176    13.17        2.59  2.37               20.0      120.0           1.65
 177    14.13        4.10  2.74               24.5       96.0           2.05

      flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
 0          3.06                  0.28             2.29             5.64  1.04
 1          2.76                  0.26             1.28             4.38  1.05
 2          3.24                  0.30             2.81             5.68  1.03
 3          3.49                  0.24             2.18             7.80  0.86
 4          2.69                  0.39             1.82             4.32  1.04
 ..          ...                   ...              ...              ...   ...
 173        0.61                  0.52             1.06             7.70  0.64
 174        0.75                  0.43             1.41             7.30  0.70
 175        0.69                  0.43             1.35            10.20  0.59
 176        0.68                  0.53             1.46             9.30  0.60
 177        0.76                  0.56             1.35             9.20  0.61

      od280/od315_of_diluted_wines  proline
 0                            3.92   1065.0
 1                            3.40   1050.0
 2                            3.17   1185.0
 3                            3.45   1480.0
 4                            2.93    735.0
 ..                            ...      ...
 173                          1.74    740.0
 174                          1.56    750.0
 175                          1.56    835.0
 176                          1.62    840.0
 177                          1.60    560.0

 [178 rows x 13 columns],
 'target': 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 173    2
 174    2
 175    2
 176    2
 177    2
 Name: target, Length: 178, dtype: int64,
 'frame':      alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
 0      14.23        1.71  2.43               15.6      127.0           2.80
 1      13.20        1.78  2.14               11.2      100.0           2.65
 2      13.16        2.36  2.67               18.6      101.0           2.80
 3      14.37        1.95  2.50               16.8      113.0           3.85
 4      13.24        2.59  2.87               21.0      118.0           2.80
 ..       ...         ...   ...                ...        ...            ...
 173    13.71        5.65  2.45               20.5       95.0           1.68
 174    13.40        3.91  2.48               23.0      102.0           1.80
 175    13.27        4.28  2.26               20.0      120.0           1.59
 176    13.17        2.59  2.37               20.0      120.0           1.65
 177    14.13        4.10  2.74               24.5       96.0           2.05

      flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
 0          3.06                  0.28             2.29             5.64  1.04
 1          2.76                  0.26             1.28             4.38  1.05
 2          3.24                  0.30             2.81             5.68  1.03
 3          3.49                  0.24             2.18             7.80  0.86
 4          2.69                  0.39             1.82             4.32  1.04
 ..          ...                   ...              ...              ...   ...
 173        0.61                  0.52             1.06             7.70  0.64
 174        0.75                  0.43             1.41             7.30  0.70
 175        0.69                  0.43             1.35            10.20  0.59
 176        0.68                  0.53             1.46             9.30  0.60
 177        0.76                  0.56             1.35             9.20  0.61

      od280/od315_of_diluted_wines  proline  target
 0                            3.92   1065.0       0
 1                            3.40   1050.0       0
 2                            3.17   1185.0       0
 3                            3.45   1480.0       0
 4                            2.93    735.0       0
 ..                            ...      ...     ...
 173                          1.74    740.0       2
 174                          1.56    750.0       2
 175                          1.56    835.0       2
 176                          1.62    840.0       2
 177                          1.60    560.0       2

 [178 rows x 14 columns],
 'target_names': array(['class_0', 'class_1', 'class_2'], dtype='<U7'),
 'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 178\n:Number of Attributes: 13 numeric, predictive attributes and the class\n:Attribute Information:\n    - Alcohol\n    - Malic acid\n    - Ash\n    - Alcalinity of ash\n    - Magnesium\n    - Total phenols\n    - Flavanoids\n    - Nonflavanoid phenols\n    - Proanthocyanins\n    - Color intensity\n    - Hue\n    - OD280/OD315 of diluted wines\n    - Proline\n    - class:\n        - class_0\n        - class_1\n        - class_2\n\n:Summary Statistics:\n\n============================= ==== ===== ======= =====\n                                Min   Max   Mean     SD\n============================= ==== ===== ======= =====\nAlcohol:                      11.0  14.8    13.0   0.8\nMalic Acid:                   0.74  5.80    2.34  1.12\nAsh:                          1.36  3.23    2.36  0.27\nAlcalinity of Ash:            10.6  30.0    19.5   3.3\nMagnesium:                    70.0 162.0    99.7  14.3\nTotal Phenols:                0.98  3.88    2.29  0.63\nFlavanoids:                   0.34  5.08    2.03  1.00\nNonflavanoid Phenols:         0.13  0.66    0.36  0.12\nProanthocyanins:              0.41  3.58    1.59  0.57\nColour Intensity:              1.3  13.0     5.1   2.3\nHue:                          0.48  1.71    0.96  0.23\nOD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\nProline:                       278  1680     746   315\n============================= ==== ===== ======= =====\n\n:Missing Attribute Values: None\n:Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners:\n\nForina, M. et al, PARVUS -\nAn Extendible Package for Data Exploration, Classification and Correlation.\nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science.\n\n.. dropdown:: References\n\n    (1) S. Aeberhard, D. Coomans and O. de Vel,\n    Comparison of Classifiers in High Dimensional Settings,\n    Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of\n    Mathematics and Statistics, James Cook University of North Queensland.\n    (Also submitted to Technometrics).\n\n    The data was used with many others for comparing various\n    classifiers. The classes are separable, though only RDA\n    has achieved 100% correct classification.\n    (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))\n    (All results using the leave-one-out technique)\n\n    (2) S. Aeberhard, D. Coomans and O. de Vel,\n    "THE CLASSIFICATION PERFORMANCE OF RDA"\n    Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of\n    Mathematics and Statistics, James Cook University of North Queensland.\n    (Also submitted to Journal of Chemometrics).\n',
 'feature_names': ['alcohol',
  'malic_acid',
  'ash',
  'alcalinity_of_ash',
  'magnesium',
  'total_phenols',
  'flavanoids',
  'nonflavanoid_phenols',
  'proanthocyanins',
  'color_intensity',
  'hue',
  'od280/od315_of_diluted_wines',
  'proline']}

In [5]:
df = an.load_datasets_digits()
df

{'data':       pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
 0           0.0        0.0        5.0       13.0        9.0        1.0
 1           0.0        0.0        0.0       12.0       13.0        5.0
 2           0.0        0.0        0.0        4.0       15.0       12.0
 3           0.0        0.0        7.0       15.0       13.0        1.0
 4           0.0        0.0        0.0        1.0       11.0        0.0
 ...         ...        ...        ...        ...        ...        ...
 1792        0.0        0.0        4.0       10.0       13.0        6.0
 1793        0.0        0.0        6.0       16.0       13.0       11.0
 1794        0.0        0.0        1.0       11.0       15.0        1.0
 1795        0.0        0.0        2.0       10.0        7.0        0.0
 1796        0.0        0.0       10.0       14.0        8.0        1.0

       pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
 0           0.0        0.0        0.0        0.0  ...        0.0        0.0
 1           0.0        0.0        0.0        0.0  ...        0.0        0.0
 2           0.0        0.0        0.0        0.0  ...        5.0        0.0
 3           0.0        0.0        0.0        8.0  ...        9.0        0.0
 4           0.0        0.0        0.0        0.0  ...        0.0        0.0
 ...         ...        ...        ...        ...  ...        ...        ...
 1792        0.0        0.0        0.0        1.0  ...        4.0        0.0
 1793        1.0        0.0        0.0        0.0  ...        1.0        0.0
 1794        0.0        0.0        0.0        0.0  ...        0.0        0.0
 1795        0.0        0.0        0.0        0.0  ...        2.0        0.0
 1796        0.0        0.0        0.0        2.0  ...        8.0        0.0

       pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
 0           0.0        0.0        6.0       13.0       10.0        0.0
 1           0.0        0.0        0.0       11.0       16.0       10.0
 2           0.0        0.0        0.0        3.0       11.0       16.0
 3           0.0        0.0        7.0       13.0       13.0        9.0
 4           0.0        0.0        0.0        2.0       16.0        4.0
 ...         ...        ...        ...        ...        ...        ...
 1792        0.0        0.0        2.0       14.0       15.0        9.0
 1793        0.0        0.0        6.0       16.0       14.0        6.0
 1794        0.0        0.0        2.0        9.0       13.0        6.0
 1795        0.0        0.0        5.0       12.0       16.0       12.0
 1796        0.0        1.0        8.0       12.0       14.0       12.0

       pixel_7_6  pixel_7_7
 0           0.0        0.0
 1           0.0        0.0
 2           9.0        0.0
 3           0.0        0.0
 4           0.0        0.0
 ...         ...        ...
 1792        0.0        0.0
 1793        0.0        0.0
 1794        0.0        0.0
 1795        0.0        0.0
 1796        1.0        0.0

 [1797 rows x 64 columns],
 'target': 0       0
 1       1
 2       2
 3       3
 4       4
        ..
 1792    9
 1793    0
 1794    8
 1795    9
 1796    8
 Name: target, Length: 1797, dtype: int64,
 'frame':       pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
 0           0.0        0.0        5.0       13.0        9.0        1.0
 1           0.0        0.0        0.0       12.0       13.0        5.0
 2           0.0        0.0        0.0        4.0       15.0       12.0
 3           0.0        0.0        7.0       15.0       13.0        1.0
 4           0.0        0.0        0.0        1.0       11.0        0.0
 ...         ...        ...        ...        ...        ...        ...
 1792        0.0        0.0        4.0       10.0       13.0        6.0
 1793        0.0        0.0        6.0       16.0       13.0       11.0
 1794        0.0        0.0        1.0       11.0       15.0        1.0
 1795        0.0        0.0        2.0       10.0        7.0        0.0
 1796        0.0        0.0       10.0       14.0        8.0        1.0

       pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
 0           0.0        0.0        0.0        0.0  ...        0.0        0.0
 1           0.0        0.0        0.0        0.0  ...        0.0        0.0
 2           0.0        0.0        0.0        0.0  ...        0.0        0.0
 3           0.0        0.0        0.0        8.0  ...        0.0        0.0
 4           0.0        0.0        0.0        0.0  ...        0.0        0.0
 ...         ...        ...        ...        ...  ...        ...        ...
 1792        0.0        0.0        0.0        1.0  ...        0.0        0.0
 1793        1.0        0.0        0.0        0.0  ...        0.0        0.0
 1794        0.0        0.0        0.0        0.0  ...        0.0        0.0
 1795        0.0        0.0        0.0        0.0  ...        0.0        0.0
 1796        0.0        0.0        0.0        2.0  ...        0.0        0.0

       pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
 0           0.0        6.0       13.0       10.0        0.0        0.0
 1           0.0        0.0       11.0       16.0       10.0        0.0
 2           0.0        0.0        3.0       11.0       16.0        9.0
 3           0.0        7.0       13.0       13.0        9.0        0.0
 4           0.0        0.0        2.0       16.0        4.0        0.0
 ...         ...        ...        ...        ...        ...        ...
 1792        0.0        2.0       14.0       15.0        9.0        0.0
 1793        0.0        6.0       16.0       14.0        6.0        0.0
 1794        0.0        2.0        9.0       13.0        6.0        0.0
 1795        0.0        5.0       12.0       16.0       12.0        0.0
 1796        1.0        8.0       12.0       14.0       12.0        1.0

       pixel_7_7  target
 0           0.0       0
 1           0.0       1
 2           0.0       2
 3           0.0       3
 4           0.0       4
 ...         ...     ...
 1792        0.0       9
 1793        0.0       0
 1794        0.0       8
 1795        0.0       9
 1796        0.0       8

 [1797 rows x 65 columns],
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
  'pixel_5_2',
  'pixel_5_3',
  'pixel_5_4',
  'pixel_5_5',
  'pixel_5_6',
  'pixel_5_7',
  'pixel_6_0',
  'pixel_6_1',
  'pixel_6_2',
  'pixel_6_3',
  'pixel_6_4',
  'pixel_6_5',
  'pixel_6_6',
  'pixel_6_7',
  'pixel_7_0',
  'pixel_7_1',
  'pixel_7_2',
  'pixel_7_3',
  'pixel_7_4',
  'pixel_7_5',
  'pixel_7_6',
  'pixel_7_7'],
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

        [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
         [ 0.,  0.,  3., ..., 14.,  0.,  0.],
         [ 0.,  0.,  8., ..., 16.,  0.,  0.],
         ...,
         [ 0.,  9., 16., ...,  0.,  0.,  0.],
         [ 0.,  3., 13., ..., 11.,  5.,  0.],
         [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

        ...,

        [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ...,  2.,  1.,  0.],
         [ 0.,  0., 16., ..., 16.,  5.,  0.],
         ...,
         [ 0.,  0., 16., ..., 15.,  0.,  0.],
         [ 0.,  0., 15., ..., 16.,  0.,  0.],
         [ 0.,  0.,  2., ...,  6.,  0.,  0.]],

        [[ 0.,  0.,  2., ...,  0.,  0.,  0.],
         [ 0.,  0., 14., ..., 15.,  1.,  0.],
         [ 0.,  4., 16., ..., 16.,  7.,  0.],
         ...,
         [ 0.,  0.,  0., ..., 16.,  2.,  0.],
         [ 0.,  0.,  4., ..., 16.,  2.,  0.],
         [ 0.,  0.,  5., ..., 12.,  0.,  0.]],

        [[ 0.,  0., 10., ...,  1.,  0.,  0.],
         [ 0.,  2., 16., ...,  1.,  0.,  0.],
         [ 0.,  0., 15., ..., 15.,  0.,  0.],
         ...,
         [ 0.,  4., 16., ..., 16.,  6.,  0.],
         [ 0.,  8., 16., ..., 16.,  8.,  0.],
         [ 0.,  1.,  8., ..., 12.,  1.,  0.]]], shape=(1797, 8, 8)),
 'DESCR': ".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 1797\n:Number of Attributes: 64\n:Attribute Information: 8x8 image of integer pixels in the range 0..16.\n:Missing Attribute Values: None\n:Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n:Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixels are counted in each block. This generates\nan input matrix of 8x8 where each element is an integer in the range\n0..16. This reduces dimensionality and gives invariance to small\ndistortions.\n\nFor info on NIST preprocessing routines, see M. D. Garris, J. L. Blue, G.\nT. Candela, D. L. Dimmick, J. Geist, P. J. Grother, S. A. Janet, and C.\nL. Wilson, NIST Form-Based Handprint Recognition System, NISTIR 5469,\n1994.\n\n.. dropdown:: References\n\n  - C. Kaynak (1995) Methods of Combining Multiple Classifiers and Their\n    Applications to Handwritten Digit Recognition, MSc Thesis, Institute of\n    Graduate Studies in Science and Engineering, Bogazici University.\n  - E. Alpaydin, C. Kaynak (1998) Cascading Classifiers, Kybernetika.\n  - Ken Tang and Ponnuthurai N. Suganthan and Xi Yao and A. Kai Qin.\n    Linear dimensionalityreduction using relevance weighted LDA. School of\n    Electrical and Electronic Engineering Nanyang Technological University.\n    2005.\n  - Claudio Gentile. A New Approximate Maximal Margin Classification\n    Algorithm. NIPS. 2000.\n"}